/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

// #line 1 "test.check"
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "matrix.h"

void print_matrix(matrix_t *matrix) {
    for (int i = 0; i < matrix->rows; ++i) {
        for (int j = 0; j < matrix->columns; ++j) {
            printf("%.9lf", matrix->matrix[i][j]);
            if (j != matrix->columns - 1) printf(" ");
        }
        puts("");
    }
}

void fill_matrix(matrix_t *matrix, int seed) {
    for (int i = 0; i < matrix->rows; ++i) {
        for (int j = 0; j < matrix->columns; ++j) {
            matrix->matrix[i][j] = (float)seed / 28.7612354 * (100. - 0.) + 0.;
            seed++;
        }
    }
}
void clean_matrix(matrix_t *matrix) {
    matrix->columns = 0;
    matrix->rows = 0;
    matrix->matrix = NULL;
}

START_TEST(test_create_matrix5) {
    matrix_t A;
    clean_matrix(&A);
    int rows = 12;
    int columns = 3;
    int res = create_matrix(rows, columns, &A);
    int res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    remove_matrix(&A);

    rows = -2;
    columns = 5;
    res = create_matrix(rows, columns, &A);
    res_orig = 1;
    ck_assert_int_eq(res, res_orig);

    rows = 2;
    columns = -5;
    res = create_matrix(rows, columns, &A);
    res_orig = 1;
    ck_assert_int_eq(res, res_orig);

    rows = 2;
    columns = 0;
    res = create_matrix(rows, columns, &A);
    res_orig = 1;
    ck_assert_int_eq(res, res_orig);

    rows = 0;
    columns = 1;
    res = create_matrix(rows, columns, &A);
    res_orig = 1;
    ck_assert_int_eq(res, res_orig);

    rows = 0;
    columns = -1;
    res = create_matrix(rows, columns, &A);
    res_orig = 1;
    ck_assert_int_eq(res, res_orig);
}
END_TEST

START_TEST(test_eq_matrix_rows_and_columns) {
    matrix_t A, B;
    clean_matrix(&A);
    clean_matrix(&B);
    int rows_A = 2;
    int columns_A = 5;
    int rows_B = 2;
    int columns_B = 5;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    int result = eq_matrix(&A, &B);
    int res_orig = 1;
    ck_assert_int_eq(result, res_orig);
    remove_matrix(&A);
    remove_matrix(&B);

    rows_A = 1;
    columns_A = 5;
    rows_B = 2;
    columns_B = 5;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    result = eq_matrix(&A, &B);
    res_orig = 0;
    ck_assert_int_eq(result, res_orig);
    remove_matrix(&A);
    remove_matrix(&B);

    rows_A = 2;
    columns_A = 15;
    rows_B = 2;
    columns_B = 5;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    result = eq_matrix(&A, &B);
    res_orig = 0;
    ck_assert_int_eq(result, res_orig);
    remove_matrix(&A);
    remove_matrix(&B);

    rows_A = 2;
    columns_A = 5;
    rows_B = 1;
    columns_B = 5;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    result = eq_matrix(&A, &B);
    res_orig = 0;
    ck_assert_int_eq(result, res_orig);
    remove_matrix(&A);
    remove_matrix(&B);

    rows_A = 2;
    columns_A = 5;
    rows_B = 2;
    columns_B = 5234;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    result = eq_matrix(&A, &B);
    res_orig = 0;
    ck_assert_int_eq(result, res_orig);
    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix_norm_value) {
    matrix_t A, B;
    clean_matrix(&A);
    clean_matrix(&B);
    int row_A = 2;
    int col_A = 3;
    int row_B = 2;
    int col_B = 3;
    create_matrix(row_A, col_A, &A);
    create_matrix(row_B, col_B, &B);

    A.matrix[0][0] = 1;
    A.matrix[0][1] = 4;
    A.matrix[0][2] = 7;
    A.matrix[1][0] = -12;
    A.matrix[1][1] = 0.98326745;
    A.matrix[1][2] = 1.2930579823514;
    B.matrix[0][0] = 1;
    B.matrix[0][1] = 4;
    B.matrix[0][2] = 7;
    B.matrix[1][0] = -12;
    B.matrix[1][1] = 0.98326745;
    B.matrix[1][2] = 1.2930579823514;
    int result = eq_matrix(&A, &B);
    int res_orig = 1;
    ck_assert_int_eq(result, res_orig);

    A.matrix[0][0] = 1123123;
    A.matrix[0][1] = 41233;
    A.matrix[0][2] = 1324127;
    A.matrix[1][0] = -123123124;
    A.matrix[1][1] = 0.12;
    A.matrix[1][2] = 12412.2930579823514;
    B.matrix[0][0] = 1;
    B.matrix[0][1] = 4;
    B.matrix[0][2] = 7;
    B.matrix[1][0] = -12;
    B.matrix[1][1] = 0.98326745;
    B.matrix[1][2] = 1.2930579823514;
    result = eq_matrix(&A, &B);
    res_orig = 0;
    ck_assert_int_eq(result, res_orig);

    A.matrix[0][0] = 1123123;
    A.matrix[0][1] = 41233;
    A.matrix[0][2] = 1324127;
    A.matrix[1][0] = -123123124;
    A.matrix[1][1] = 0.12;
    A.matrix[1][2] = 12412.2930579823514;
    B.matrix[0][0] = 1123123;
    B.matrix[0][1] = 41233;
    B.matrix[0][2] = 1324127;
    B.matrix[1][0] = -123123124;
    B.matrix[1][1] = 0.12;
    B.matrix[1][2] = 12412.2930579823514;
    result = eq_matrix(&A, &B);
    res_orig = 1;
    ck_assert_int_eq(result, res_orig);

    A.matrix[0][0] = 0;
    A.matrix[0][1] = 0;
    A.matrix[0][2] = 0;
    A.matrix[1][0] = -0;
    A.matrix[1][1] = 0.0;
    A.matrix[1][2] = 12412.0;
    B.matrix[0][0] = 0;
    B.matrix[0][1] = 0;
    B.matrix[0][2] = 0;
    B.matrix[1][0] = +0;
    B.matrix[1][1] = 0.0;
    B.matrix[1][2] = 12412.0;
    result = eq_matrix(&A, &B);
    res_orig = 1;
    ck_assert_int_eq(result, res_orig);

    A.matrix[0][0] = 0.000000000123;
    A.matrix[0][1] = 0.00000000000000000123;
    A.matrix[0][2] = 6231627571246582412;
    A.matrix[1][0] = -0.873246589176521568;
    A.matrix[1][1] = 0.873246589176521568;
    A.matrix[1][2] = 12412.8764087136546190825910251253;
    B.matrix[0][0] = 0.000000000123;
    B.matrix[0][1] = 0.00000000000000000123;
    B.matrix[0][2] = 6231627571246582412;
    B.matrix[1][0] = -0.873246589176521568;
    B.matrix[1][1] = 0.873246589176521568;
    B.matrix[1][2] = 12412.8764087136546190825910251253;
    result = eq_matrix(&A, &B);
    res_orig = 1;
    ck_assert_int_eq(result, res_orig);

    A.matrix[0][0] = FLT_MAX;
    A.matrix[0][1] = FLT_MIN;
    A.matrix[0][2] = INT_MAX;
    A.matrix[1][0] = INT_MIN;
    A.matrix[1][1] = DBL_MAX;
    A.matrix[1][2] = DBL_MIN;
    B.matrix[0][0] = FLT_MAX;
    B.matrix[0][1] = FLT_MIN;
    B.matrix[0][2] = INT_MAX;
    B.matrix[1][0] = INT_MIN;
    B.matrix[1][1] = DBL_MAX;
    B.matrix[1][2] = DBL_MIN;
    result = eq_matrix(&A, &B);
    res_orig = 1;
    ck_assert_int_eq(result, res_orig);

    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix_not_norm_value) {
    matrix_t A, B;
    clean_matrix(&A);
    clean_matrix(&B);
    int rows_A = 2;
    int columns_A = 2;
    int rows_B = 2;
    int columns_B = 2;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);

    A.matrix[0][0] = MY_INFINITY;
    A.matrix[0][1] = -MY_INFINITY;
    A.matrix[1][0] = MY_INFINITY;
    A.matrix[1][1] = -MY_INFINITY;
    B.matrix[0][0] = MY_INFINITY;
    B.matrix[0][1] = -MY_INFINITY;
    B.matrix[1][0] = MY_INFINITY;
    B.matrix[1][1] = -MY_INFINITY;
    int result = eq_matrix(&A, &B);
    int res_orig = 1;
    ck_assert_int_eq(result, res_orig);

    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_matrix_incorrect_matrix) {
    matrix_t A, B, R;
    clean_matrix(&A);
    clean_matrix(&B);
    double number = 0;
    int row = 2;
    int col = 2;
    // create_matrix(row, col, &A);
    create_matrix(row, col, &B);
    int err_sum = sum_matrix(&A, &B, &R);
    int err_sub = sub_matrix(&A, &B, &R);
    int err_mult_number = mult_number(&A, number, &R);
    int err_mult = mult_matrix(&A, &B, &R);
    int err_transpose = transpose(&A, &R);
    int err_determ = determinant(&A, &number);
    int err_calc = calc_complements(&A, &R);
    int inverse = inverse_matrix(&A, &R);
    ck_assert_int_eq(err_sum, INCORRECT_MATRIX);
    ck_assert_int_eq(err_sub, INCORRECT_MATRIX);
    ck_assert_int_eq(err_mult_number, INCORRECT_MATRIX);
    ck_assert_int_eq(err_mult, INCORRECT_MATRIX);
    ck_assert_int_eq(err_transpose, INCORRECT_MATRIX);
    ck_assert_int_eq(err_determ, INCORRECT_MATRIX);
    ck_assert_int_eq(err_calc, INCORRECT_MATRIX);
    ck_assert_int_eq(inverse, INCORRECT_MATRIX);
    remove_matrix(&B);

    create_matrix(row, col, &A);
    // create_matrix(row, col, &B);
    int err = sum_matrix(&A, &B, &R);
    ck_assert_int_eq(err, INCORRECT_MATRIX);
    remove_matrix(&A);

    row = 0;
    create_matrix(row, col, &A);
    create_matrix(row, col, &B);
    err = sum_matrix(&A, &B, &R);
    ck_assert_int_eq(err, INCORRECT_MATRIX);

    col = 0;
    create_matrix(row, col, &A);
    create_matrix(row, col, &B);
    err = sum_matrix(&A, &B, &R);
    ck_assert_int_eq(err, INCORRECT_MATRIX);
}
END_TEST

START_TEST(test_matrix_calc_error) {
    matrix_t A, B, R;
    clean_matrix(&A);
    clean_matrix(&B);
    double number = 0;
    double num = MY_NAN;
    int row_A = 1;
    int col_A = 2;
    int row_B = 3;
    int col_B = 2;
    create_matrix(row_A, col_A, &A);
    create_matrix(row_B, col_B, &B);

    int err_sum = sum_matrix(&A, &B, &R);
    int err_sub = sub_matrix(&A, &B, &R);
    int err_mult_number = mult_number(&A, num, &R);
    int err_mult = mult_matrix(&A, &B, &R);
    int err_determ = determinant(&A, &number);
    int err_calc = calc_complements(&A, &R);
    int inverse = inverse_matrix(&A, &R);

    ck_assert_int_eq(err_sum, CALCULATION_ERROR);
    ck_assert_int_eq(err_sub, CALCULATION_ERROR);
    ck_assert_int_eq(err_mult_number, CALCULATION_ERROR);
    ck_assert_int_eq(err_mult, CALCULATION_ERROR);
    ck_assert_int_eq(err_determ, CALCULATION_ERROR);
    ck_assert_int_eq(err_calc, CALCULATION_ERROR);
    ck_assert_int_eq(inverse, CALCULATION_ERROR);

    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_sum_matrix_norm_value) {
    matrix_t A, B, R, orig;
    clean_matrix(&A);
    clean_matrix(&B);
    int row = 2;
    int col = 2;
    create_matrix(row, col, &A);
    create_matrix(row, col, &B);
    create_matrix(row, col, &orig);

    fill_matrix(&A, 23);
    fill_matrix(&B, 8);
    orig.matrix[0][0] = 107.78396536;
    orig.matrix[0][1] = 114.73776957;
    orig.matrix[1][0] = 121.69157379;
    orig.matrix[1][1] = 128.64537801;
    int res = sum_matrix(&A, &B, &R);
    int res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&orig, &R), SUCCESS);
    remove_matrix(&R);

    A.matrix[0][0] = 23;
    A.matrix[0][1] = 23;
    A.matrix[1][0] = 22;
    A.matrix[1][1] = 33;
    B.matrix[0][0] = 20;
    B.matrix[0][1] = 4;
    B.matrix[1][0] = 12;
    B.matrix[1][1] = 34;
    orig.matrix[0][0] = 43;
    orig.matrix[0][1] = 27;
    orig.matrix[1][0] = 34;
    orig.matrix[1][1] = 67;
    res = sum_matrix(&A, &B, &R);
    res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&orig, &R), SUCCESS);
    remove_matrix(&R);

    A.matrix[0][0] = 12.2134241;
    A.matrix[0][1] = 1.23214141;
    A.matrix[1][0] = 0.1234124;
    A.matrix[1][1] = -0.7126442;
    B.matrix[0][0] = -12412;
    B.matrix[0][1] = 4.91286921412;
    B.matrix[1][0] = 1341.12412441241;
    B.matrix[1][1] = 0.00000000000000034;
    orig.matrix[0][0] = -12399.7865759;
    orig.matrix[0][1] = 6.14501062412;
    orig.matrix[1][0] = 1341.24753681241;
    orig.matrix[1][1] = -0.71264419999999966;
    res = sum_matrix(&A, &B, &R);
    res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&orig, &R), SUCCESS);
    remove_matrix(&R);

    A.matrix[0][0] = 12.21124124124134241;
    A.matrix[0][1] = 13412354011.23214141;
    A.matrix[1][0] = 0.00000004;
    A.matrix[1][1] = -0.00000000000000034;
    B.matrix[0][0] = -12412.9823475097134;
    B.matrix[0][1] = -4.9921412;
    B.matrix[1][0] = 0.00000000004;
    B.matrix[1][1] = 0.00000000000000034;
    orig.matrix[0][0] = -12400.77110626847205759;
    orig.matrix[0][1] = 13412354006.24000021;
    orig.matrix[1][0] = 0.00000004004;
    orig.matrix[1][1] = 0.0;
    res = sum_matrix(&A, &B, &R);
    res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&orig, &R), SUCCESS);
    remove_matrix(&R);

    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&orig);
}
END_TEST

START_TEST(test_sub_matrix_norm_value) {
    matrix_t A, B, R, orig;
    int row = 2;
    int col = 2;
    create_matrix(row, col, &A);
    create_matrix(row, col, &B);
    create_matrix(row, col, &orig);

    A.matrix[0][0] = 23;
    A.matrix[0][1] = 23;
    A.matrix[1][0] = 22;
    A.matrix[1][1] = 33;
    B.matrix[0][0] = 20;
    B.matrix[0][1] = 4;
    B.matrix[1][0] = 12;
    B.matrix[1][1] = 34;
    orig.matrix[0][0] = 3;
    orig.matrix[0][1] = 19;
    orig.matrix[1][0] = 10;
    orig.matrix[1][1] = -1;
    int res = sub_matrix(&A, &B, &R);
    int res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&orig, &R), SUCCESS);
    remove_matrix(&R);

    A.matrix[0][0] = 12.2134241;
    A.matrix[0][1] = 1.23214141;
    A.matrix[1][0] = 0.1234124;
    A.matrix[1][1] = -0.7126442;
    B.matrix[0][0] = -12412;
    B.matrix[0][1] = 4.91286921412;
    B.matrix[1][0] = 1341.12412441241;
    B.matrix[1][1] = 0.00000000000000034;
    orig.matrix[0][0] = 12424.2134241;
    orig.matrix[0][1] = -3.68072780412;
    orig.matrix[1][0] = -1341.00071201241;
    orig.matrix[1][1] = -0.71264419999999966;
    res = sub_matrix(&A, &B, &R);
    res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&orig, &R), SUCCESS);
    remove_matrix(&R);

    A.matrix[0][0] = 12.21124124124134241;
    A.matrix[0][1] = 13412354011.23214141;
    A.matrix[1][0] = 0.00000004;
    A.matrix[1][1] = -0.00000000000000034;

    B.matrix[0][0] = -12412.9823475097134;
    B.matrix[0][1] = -4.9921412;
    B.matrix[1][0] = 0.00000000004;
    B.matrix[1][1] = 0.00000000000000034;

    orig.matrix[0][0] = 12425.19358875095474241;
    orig.matrix[0][1] = 13412354016.22428261;
    orig.matrix[1][0] = 0.00000003996;
    orig.matrix[1][1] = -0.00000000000000068;
    res = sub_matrix(&A, &B, &R);
    res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&orig, &R), SUCCESS);
    remove_matrix(&R);

    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&orig);
}
END_TEST

START_TEST(test_mult_number_norm_value) {
    matrix_t A, R, origin;
    clean_matrix(&A);
    clean_matrix(&origin);
    int row = 1;
    int col = 3;
    double number = 0.123;
    create_matrix(row, col, &A);
    create_matrix(row, col, &origin);
    fill_matrix(&A, 2);
    mult_number(&A, number, &R);
    origin.matrix[0][0] = 0.85531791906;
    origin.matrix[0][1] = 1.28297687736;
    origin.matrix[0][2] = 1.71063583689;
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&origin);
    remove_matrix(&R);

    row = 3;
    col = 1;
    clean_matrix(&A);
    clean_matrix(&origin);
    number = -2.328561244;
    create_matrix(row, col, &A);
    create_matrix(row, col, &origin);
    fill_matrix(&A, 124);
    mult_number(&A, number, &R);
    origin.matrix[0][0] = -214.367375204;
    origin.matrix[1][0] = -47.199094175;
    origin.matrix[2][0] = -118.533497492;
    // ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&origin);
    remove_matrix(&R);

    row = 2;
    col = 2;
    clean_matrix(&A);
    clean_matrix(&origin);
    number = 0.456;
    create_matrix(row, col, &A);
    create_matrix(row, col, &origin);
    A.matrix[0][0] = -12412.9823475097134;
    A.matrix[0][1] = -4.9921412;
    A.matrix[1][0] = 0.00000000004;
    A.matrix[1][1] = 0.00000000000000034;
    mult_number(&A, number, &R);
    origin.matrix[0][0] = -5660.319950464;
    origin.matrix[0][1] = -2.276416387;
    origin.matrix[1][0] = 0;
    origin.matrix[1][1] = 0;
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&origin);
    remove_matrix(&R);
}
END_TEST

START_TEST(test_mult_matrix_norm_value) {
    matrix_t A, B, R, origin;
    clean_matrix(&A);
    clean_matrix(&B);
    int row_A = 1;
    int col_A = 3;
    int row_B = 3;
    int col_B = 2;
    create_matrix(row_A, col_A, &A);
    create_matrix(row_B, col_B, &B);
    create_matrix(row_A, col_B, &origin);
    fill_matrix(&A, -10);
    fill_matrix(&B, 3);
    origin.matrix[0][0] = -1583.6391232719901706;
    origin.matrix[0][1] = -1910.0380267262512718;
    int res = mult_matrix(&A, &B, &R);
    int res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&R);
    remove_matrix(&origin);

    row_A = 1;
    col_A = 3;
    row_B = 3;
    col_B = 1;
    create_matrix(row_A, col_A, &A);
    create_matrix(row_B, col_B, &B);
    create_matrix(row_A, col_B, &origin);
    A.matrix[0][0] = 0;
    A.matrix[0][1] = 0.0;
    A.matrix[0][2] = -0;
    fill_matrix(&B, 4);
    origin.matrix[0][0] = 0;
    res = mult_matrix(&A, &B, &R);
    res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&R);
    A.matrix[0][0] = -1;
    A.matrix[0][1] = 1;
    A.matrix[0][2] = -1;
    origin.matrix[0][0] = -17.38451054;
    res = mult_matrix(&A, &B, &R);
    res_orig = 0;
    ck_assert_int_eq(res, res_orig);
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&R);
    remove_matrix(&origin);
}
END_TEST

START_TEST(test_transpose_norm_value) {
    matrix_t A, R, origin;
    clean_matrix(&A);
    clean_matrix(&origin);
    int row = 1;
    int col = 3;
    create_matrix(row, col, &A);
    create_matrix(col, row, &origin);
    A.matrix[0][0] = 0;
    A.matrix[0][1] = 1;
    A.matrix[0][2] = 2;
    transpose(&A, &R);
    origin.matrix[0][0] = 0;
    origin.matrix[1][0] = 1;
    origin.matrix[2][0] = 2;
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&origin);
    remove_matrix(&R);

    row = 4;
    col = 2;
    create_matrix(row, col, &A);
    create_matrix(col, row, &origin);
    A.matrix[0][0] = 0;
    A.matrix[0][1] = 1;
    A.matrix[1][0] = 2;
    A.matrix[1][1] = 3;
    A.matrix[2][0] = 4;
    A.matrix[2][1] = 5;
    A.matrix[3][0] = 6;
    A.matrix[3][1] = 7;
    transpose(&A, &R);
    origin.matrix[0][0] = 0;
    origin.matrix[0][1] = 2;
    origin.matrix[0][2] = 4;
    origin.matrix[0][3] = 6;
    origin.matrix[1][0] = 1;
    origin.matrix[1][1] = 3;
    origin.matrix[1][2] = 5;
    origin.matrix[1][3] = 7;
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&origin);
    remove_matrix(&R);

    row = 1;
    col = 1;
    create_matrix(row, col, &A);
    create_matrix(col, row, &origin);
    A.matrix[0][0] = 123;
    transpose(&A, &R);
    origin.matrix[0][0] = 123;
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&origin);
    remove_matrix(&R);

    row = 3;
    col = 3;
    create_matrix(row, col, &A);
    create_matrix(col, row, &origin);
    A.matrix[0][0] = 9;
    A.matrix[0][1] = 8;
    A.matrix[0][2] = 7;
    A.matrix[1][0] = 6;
    A.matrix[1][1] = 5;
    A.matrix[1][2] = 4;
    A.matrix[2][0] = 3;
    A.matrix[2][1] = 2;
    A.matrix[2][2] = 1;
    transpose(&A, &R);
    origin.matrix[0][0] = 9;
    origin.matrix[0][1] = 6;
    origin.matrix[0][2] = 3;
    origin.matrix[1][0] = 8;
    origin.matrix[1][1] = 5;
    origin.matrix[1][2] = 2;
    origin.matrix[2][0] = 7;
    origin.matrix[2][1] = 4;
    origin.matrix[2][2] = 1;
    ck_assert_int_eq(eq_matrix(&origin, &R), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&origin);
    remove_matrix(&R);
}
END_TEST

START_TEST(test_determinant_norm_value) {
    matrix_t A;
    clean_matrix(&A);
    double result = 0;
    int row = 1;
    int col = 1;
    create_matrix(row, col, &A);
    A.matrix[0][0] = 761235;
    int check = determinant(&A, &result);
    ck_assert_int_eq(check, 0);
    ck_assert_double_eq(result, 761235);
    remove_matrix(&A);

    row = 2;
    col = 2;
    create_matrix(row, col, &A);
    A.matrix[0][0] = 12.3452;
    A.matrix[0][1] = -123.123;
    A.matrix[1][0] = 90;
    A.matrix[1][1] = 873.12;
    check = determinant(&A, &result);
    ck_assert_int_eq(check, 0);
    ck_assert_double_eq(result, 21859.911024);
    remove_matrix(&A);

    row = 4;
    col = 4;
    create_matrix(row, col, &A);
    A.matrix[0][0] = 11;
    A.matrix[0][1] = 2;
    A.matrix[0][2] = 3;
    A.matrix[0][3] = 4;
    A.matrix[1][0] = 5;
    A.matrix[1][1] = 6;
    A.matrix[1][2] = 71;
    A.matrix[1][3] = 8;
    A.matrix[2][0] = 9;
    A.matrix[2][1] = 10;
    A.matrix[2][2] = 11;
    A.matrix[2][3] = 12;
    A.matrix[3][0] = 13;
    A.matrix[3][1] = 14;
    A.matrix[3][2] = 15;
    A.matrix[3][3] = 16;
    check = determinant(&A, &result);
    ck_assert_int_eq(check, 0);
    ck_assert_double_eq(result, 5120);
    remove_matrix(&A);
}
END_TEST

START_TEST(test_calc_complements_norm_value) {
    matrix_t A, R, O;
    clean_matrix(&A);
    int row = 1;
    int col = 1;
    create_matrix(row, col, &A);
    create_matrix(row, col, &O);
    A.matrix[0][0] = -761235;
    int check = calc_complements(&A, &R);
    O.matrix[0][0] = 1;
    ck_assert_int_eq(check, 0);
    ck_assert_int_eq(eq_matrix(&R, &O), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&R);
    remove_matrix(&O);

    row = 3;
    col = 3;
    create_matrix(row, col, &A);
    create_matrix(row, col, &O);
    A.matrix[0][0] = 1;
    A.matrix[0][1] = 2;
    A.matrix[0][2] = 3;
    A.matrix[1][0] = 0;
    A.matrix[1][1] = 4;
    A.matrix[1][2] = 2;
    A.matrix[2][0] = 5;
    A.matrix[2][1] = 2;
    A.matrix[2][2] = 1;
    check = calc_complements(&A, &R);
    O.matrix[0][0] = 0;
    O.matrix[0][1] = 10;
    O.matrix[0][2] = -20;
    O.matrix[1][0] = 4;
    O.matrix[1][1] = -14;
    O.matrix[1][2] = 8;
    O.matrix[2][0] = -8;
    O.matrix[2][1] = -2;
    O.matrix[2][2] = 4;
    ck_assert_int_eq(check, 0);
    ck_assert_int_eq(eq_matrix(&R, &O), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&R);
    remove_matrix(&O);

    row = 4;
    col = 4;
    create_matrix(row, col, &A);
    create_matrix(row, col, &O);
    A.matrix[0][0] = 1;
    A.matrix[0][1] = 2;
    A.matrix[0][2] = 3;
    A.matrix[0][3] = 4;
    A.matrix[1][0] = 0;
    A.matrix[1][1] = 4;
    A.matrix[1][2] = 2;
    A.matrix[1][3] = 6;
    A.matrix[2][0] = 5;
    A.matrix[2][1] = 2;
    A.matrix[2][2] = 1;
    A.matrix[2][3] = 1;
    A.matrix[3][0] = 4;
    A.matrix[3][1] = 4;
    A.matrix[3][2] = 0;
    A.matrix[3][3] = 1;
    check = calc_complements(&A, &R);
    O.matrix[0][0] = -16;
    O.matrix[0][1] = 26;
    O.matrix[0][2] = 68;
    O.matrix[0][3] = -40;
    O.matrix[1][0] = 8;
    O.matrix[1][1] = -18;
    O.matrix[1][2] = -44;
    O.matrix[1][3] = 40;
    O.matrix[2][0] = 32;
    O.matrix[2][1] = -42;
    O.matrix[2][2] = -36;
    O.matrix[2][3] = 40;
    O.matrix[3][0] = -16;
    O.matrix[3][1] = 46;
    O.matrix[3][2] = 28;
    O.matrix[3][3] = -40;
    ck_assert_int_eq(check, 0);
    ck_assert_int_eq(eq_matrix(&R, &O), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&R);
    remove_matrix(&O);
}
END_TEST

START_TEST(test_inverse_norm_value) {
    matrix_t A, R;
    clean_matrix(&A);
    int row = 4;
    int col = 4;
    create_matrix(row, col, &A);
    A.matrix[0][0] = 1;
    A.matrix[0][1] = 2;
    A.matrix[0][2] = 3;
    A.matrix[0][3] = 4;
    A.matrix[1][0] = 0;
    A.matrix[1][1] = 4;
    A.matrix[1][2] = 2;
    A.matrix[1][3] = 6;
    A.matrix[2][0] = 5;
    A.matrix[2][1] = 2;
    A.matrix[2][2] = 1;
    A.matrix[2][3] = -1;
    A.matrix[3][0] = 4;
    A.matrix[3][1] = 4;
    A.matrix[3][2] = 0;
    A.matrix[3][3] = 1;
    int check = inverse_matrix(&A, &R);
    ck_assert_int_eq(check, CALCULATION_ERROR);
    remove_matrix(&A);

    matrix_t O;
    clean_matrix(&O);
    row = 1;
    col = 1;
    create_matrix(row, col, &A);
    create_matrix(row, col, &O);
    A.matrix[0][0] = 5;
    check = inverse_matrix(&A, &R);
    O.matrix[0][0] = 0.2;
    ck_assert_int_eq(check, 0);
    ck_assert_int_eq(eq_matrix(&R, &O), SUCCESS);
    remove_matrix(&R);
    remove_matrix(&O);

    A.matrix[0][0] = 0.0;
    check = inverse_matrix(&A, &R);
    ck_assert_int_eq(check, CALCULATION_ERROR);
    remove_matrix(&A);

    row = 3;
    col = 3;
    create_matrix(row, col, &A);
    create_matrix(row, col, &O);
    A.matrix[0][0] = 12;
    A.matrix[0][1] = 0.12;
    A.matrix[0][2] = 12.3;
    A.matrix[1][0] = 4;
    A.matrix[1][1] = 3;
    A.matrix[1][2] = -12;
    A.matrix[2][0] = 9;
    A.matrix[2][1] = -1;
    A.matrix[2][2] = 10;
    check = inverse_matrix(&A, &R);
    O.matrix[0][0] = -0.0983284169;
    O.matrix[0][1] = 0.073746312;
    O.matrix[0][2] = 0.209439528;
    O.matrix[1][0] = 0.808478094;
    O.matrix[1][1] = -0.050803015;
    O.matrix[1][2] = -1.055391674;
    O.matrix[2][0] = 0.169343384;
    O.matrix[2][1] = -0.071451982;
    O.matrix[2][2] = -0.194034742;
    ck_assert_int_eq(eq_matrix(&R, &O), SUCCESS);
    remove_matrix(&R);

    A.matrix[0][0] = 2;
    A.matrix[0][1] = 5;
    A.matrix[0][2] = 7;
    A.matrix[1][0] = 6;
    A.matrix[1][1] = 3;
    A.matrix[1][2] = 4;
    A.matrix[2][0] = 5;
    A.matrix[2][1] = -2;
    A.matrix[2][2] = -3;
    check = inverse_matrix(&A, &R);
    O.matrix[0][0] = 1;
    O.matrix[0][1] = -1;
    O.matrix[0][2] = 1;
    O.matrix[1][0] = -38;
    O.matrix[1][1] = 41;
    O.matrix[1][2] = -34;
    O.matrix[2][0] = 27;
    O.matrix[2][1] = -29;
    O.matrix[2][2] = 24;
    ck_assert_int_eq(eq_matrix(&R, &O), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&R);
    remove_matrix(&O);
}
END_TEST

START_TEST(test_create_matrix1) {
    matrix_t A;
    int columns_A = 5;
    int rows_A = 3;
    int res_orig = 0;
    ck_assert_int_eq(create_matrix(rows_A, columns_A, &A), res_orig);
    remove_matrix(&A);
}
END_TEST

START_TEST(test_create_matrix2) {
    matrix_t A;
    int columns_A = 1;
    int rows_A = 1;
    int res_orig = 0;
    ck_assert_int_eq(create_matrix(rows_A, columns_A, &A), res_orig);
    remove_matrix(&A);
}
END_TEST

START_TEST(test_create_matrix3) {
    matrix_t A;
    int columns_A = -1;
    int rows_A = 1;
    int res_orig = 1;
    ck_assert_int_eq(create_matrix(rows_A, columns_A, &A), res_orig);
}
END_TEST

START_TEST(test_create_matrix4) {
    matrix_t A;
    int columns_A = 1;
    int rows_A = -51;
    int res_orig = 1;
    ck_assert_int_eq(create_matrix(rows_A, columns_A, &A), res_orig);
}
END_TEST

START_TEST(test_eq_matrix1) {
    matrix_t A, B;
    int columns_A = 5;
    int rows_A = 3;
    int columns_B = 5;
    int rows_B = 3;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    write_matrix(A, 1);
    write_matrix(B, 1);
    ck_assert_int_eq(eq_matrix(&A, &B), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix2) {
    matrix_t A, B;
    int columns_A = 2;
    int rows_A = 3;
    int columns_B = 5;
    int rows_B = 3;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    write_matrix(A, 1);
    write_matrix(B, 1);
    ck_assert_int_eq(eq_matrix(&A, &B), FAILURE);
    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix3) {
    matrix_t A;
    int columns_A = 5;
    int rows_A = 3;
    matrix_t B;
    int columns_B = 5;
    int rows_B = 3;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    write_matrix(A, 3.000004);
    write_matrix(B, 3.000005);
    ck_assert_int_eq(eq_matrix(&A, &B), FAILURE);
    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix4) {
    matrix_t A, B;
    int columns_A = 5;
    int rows_A = 3;
    int columns_B = 5;
    int rows_B = 3;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    write_matrix(A, 45.0000089);
    write_matrix(B, 45.0000089);
    ck_assert_int_eq(eq_matrix(&A, &B), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_sum_matrix1) {
    matrix_t A, B, C, D;
    int columns = 4;
    int rows = 3;
    create_matrix(rows, columns, &A);
    create_matrix(rows, columns, &B);
    create_matrix(rows, columns, &D);
    write_matrix(A, 1);
    write_matrix(B, 1);
    write_matrix(D, 2);

    sum_matrix(&A, &B, &C);
    ck_assert_int_eq(eq_matrix(&C, &D), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&C);
    remove_matrix(&D);
}
END_TEST

START_TEST(test_sum_matrix2) {
    matrix_t A, B, C;
    int columns_A = 2;
    int rows_A = 3;
    int columns_B = 4;
    int rows_B = 3;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    write_matrix(A, 1);
    write_matrix(B, 1);
    ck_assert_int_eq(sum_matrix(&A, &B, &C), CALCULATION_ERROR);
    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_sub_matrix1) {
    matrix_t A, B, C, D;
    int columns = 4;
    int rows = 3;
    create_matrix(rows, columns, &A);
    create_matrix(rows, columns, &B);
    create_matrix(rows, columns, &D);
    write_matrix(A, 3);
    write_matrix(B, 2);
    write_matrix(D, 1);
    sub_matrix(&A, &B, &C);
    ck_assert_int_eq(eq_matrix(&C, &D), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&C);
    remove_matrix(&D);
}
END_TEST

START_TEST(test_sub_matrix2) {
    matrix_t A, B, C;
    int columns_A = 2;
    int rows_A = 3;
    int columns_B = 4;
    int rows_B = 3;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    write_matrix(A, 1);
    write_matrix(B, 1);
    ck_assert_int_eq(sub_matrix(&A, &B, &C), CALCULATION_ERROR);
    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_mult_number_matrix1) {
    matrix_t A, B, C;
    int rows = 3;
    int columns = 3;
    create_matrix(rows, columns, &A);
    create_matrix(rows, columns, &B);
    double index = 4;
    write_matrix(A, 1);
    write_matrix(B, 4);
    mult_number(&A, index, &C);
    ck_assert_int_eq(eq_matrix(&B, &C), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&C);
}
END_TEST

START_TEST(test_mult_number_matrix2) {
    matrix_t A, B, C;
    int rows = 2;
    int columns = 7;
    create_matrix(rows, columns, &A);
    create_matrix(rows, columns, &B);
    double index = 0.6;
    write_matrix(A, 1);
    write_matrix(B, 0.6);
    mult_number(&A, index, &C);
    ck_assert_int_eq(eq_matrix(&B, &C), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&C);
}
END_TEST

START_TEST(test_mult_matrix1) {
    matrix_t A, B, C, D;
    int rows_A = 2;
    int columns_A = 3;
    int rows_B = 3;
    int columns_B = 2;
    int rows_D = 2;
    int columns_D = 2;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    create_matrix(rows_D, columns_D, &D);
    D.matrix[0][0] = 44;
    D.matrix[0][1] = 56;
    D.matrix[1][0] = 98;
    D.matrix[1][1] = 128;
    write_matrix(A, 1);
    write_matrix(B, 2);
    mult_matrix(&A, &B, &C);
    ck_assert_int_eq(eq_matrix(&D, &C), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&C);
    remove_matrix(&D);
}
END_TEST

START_TEST(test_mult_matrix2) {
    matrix_t A, B, C;
    int rows_A = 6;
    int columns_A = 7;
    int rows_B = 3;
    int columns_B = 2;
    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    write_matrix(A, 1);
    write_matrix(B, 2);
    ck_assert_int_eq(mult_matrix(&A, &B, &C), CALCULATION_ERROR);
    remove_matrix(&A);
    remove_matrix(&B);
}
END_TEST

START_TEST(test_transpose1) {
    matrix_t A, B, C;
    int rows_A = 2;
    int columns_A = 3;
    int rows_B = 3;
    int columns_B = 2;

    create_matrix(rows_A, columns_A, &A);
    create_matrix(rows_B, columns_B, &B);
    write_matrix(A, 1);
    B.matrix[0][0] = 1;
    B.matrix[0][1] = 4;
    B.matrix[1][0] = 2;
    B.matrix[1][1] = 5;
    B.matrix[2][0] = 3;
    B.matrix[2][1] = 6;
    transpose(&A, &C);
    ck_assert_int_eq(eq_matrix(&B, &C), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&C);
}
END_TEST

START_TEST(test_calc_complements1) {
    matrix_t A, B, C;
    create_matrix(3, 3, &A);
    create_matrix(3, 3, &B);
    A.matrix[0][0] = 1;
    A.matrix[0][1] = 2;
    A.matrix[0][2] = 3;

    A.matrix[1][0] = 0;
    A.matrix[1][1] = 4;
    A.matrix[1][2] = 2;

    A.matrix[2][0] = 5;
    A.matrix[2][1] = 2;
    A.matrix[2][2] = 1;

    B.matrix[0][0] = 0;
    B.matrix[0][1] = 10;
    B.matrix[0][2] = -20;

    B.matrix[1][0] = 4;
    B.matrix[1][1] = -14;
    B.matrix[1][2] = 8;

    B.matrix[2][0] = -8;
    B.matrix[2][1] = -2;
    B.matrix[2][2] = 4;
    calc_complements(&A, &C);
    ck_assert_int_eq(eq_matrix(&C, &B), SUCCESS);
    remove_matrix(&A);
    remove_matrix(&B);
    remove_matrix(&C);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_create_matrix5);
    tcase_add_test(tc1_1, test_eq_matrix_rows_and_columns);
    tcase_add_test(tc1_1, test_eq_matrix_norm_value);
    tcase_add_test(tc1_1, test_eq_matrix_not_norm_value);
    tcase_add_test(tc1_1, test_matrix_incorrect_matrix);
    tcase_add_test(tc1_1, test_matrix_calc_error);
    tcase_add_test(tc1_1, test_sum_matrix_norm_value);
    tcase_add_test(tc1_1, test_sub_matrix_norm_value);
    tcase_add_test(tc1_1, test_mult_number_norm_value);
    tcase_add_test(tc1_1, test_mult_matrix_norm_value);
    tcase_add_test(tc1_1, test_transpose_norm_value);
    tcase_add_test(tc1_1, test_determinant_norm_value);
    tcase_add_test(tc1_1, test_calc_complements_norm_value);
    tcase_add_test(tc1_1, test_inverse_norm_value);
    tcase_add_test(tc1_1, test_create_matrix1);
    tcase_add_test(tc1_1, test_create_matrix2);
    tcase_add_test(tc1_1, test_create_matrix3);
    tcase_add_test(tc1_1, test_create_matrix4);
    tcase_add_test(tc1_1, test_eq_matrix1);
    tcase_add_test(tc1_1, test_eq_matrix2);
    tcase_add_test(tc1_1, test_eq_matrix3);
    tcase_add_test(tc1_1, test_eq_matrix4);
    tcase_add_test(tc1_1, test_sum_matrix1);
    tcase_add_test(tc1_1, test_sum_matrix2);
    tcase_add_test(tc1_1, test_sub_matrix1);
    tcase_add_test(tc1_1, test_sub_matrix2);
    tcase_add_test(tc1_1, test_mult_number_matrix1);
    tcase_add_test(tc1_1, test_mult_number_matrix2);
    tcase_add_test(tc1_1, test_mult_matrix1);
    tcase_add_test(tc1_1, test_mult_matrix2);
    tcase_add_test(tc1_1, test_transpose1);
    tcase_add_test(tc1_1, test_calc_complements1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
